[versions]
jetbrains-compose = "1.5.1"
kobweb = "0.14.0"
kotlin = "1.9.10"
mongodb = "4.10.1"
kotlinx-serialization = "1.6.0"
serialization-plugin = "1.9.0"
ktor-version="2.3.4"
ballast-version="4.0.0"
kotlinx-datetime="0.4.1"

[libraries]
kobweb-api = { module = "com.varabyte.kobweb:kobweb-api", version.ref = "kobweb" }
kobweb-core = { module = "com.varabyte.kobweb:kobweb-core ", version.ref = "kobweb" }
kobweb-silk-core = { module = "com.varabyte.kobweb:kobweb-silk", version.ref = "kobweb" }
kobweb-silk-icons-fa = { module = "com.varabyte.kobweb:kobweb-silk-icons-fa", version.ref = "kobweb" }
kobweb-silk-icons-mdi = { module = "com.varabyte.kobweb:kobweb-silk-icons-mdi", version.ref = "kobweb" }
kobwebx-markdown = { module = "com.varabyte.kobwebx:kobwebx-markdown", version.ref = "kobweb" }
kotlin-mongodb = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongodb" }
kotlinx-serialization= { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-core= { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-client-js= { module = "io.ktor:ktor-client-js", version.ref = "ktor-version" }
ktor-client-logging= { module = "io.ktor:ktor-client-logging", version.ref = "ktor-version" }
ktor-client-serialization= { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
ktor-content-negotiation= { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ballast-core= { module = "io.github.copper-leaf:ballast-core", version.ref = "ballast-version" }
ballast-saved-state= { module = "io.github.copper-leaf:ballast-saved-state", version.ref = "ballast-version" }
kotlinx-datetime= { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kobweb-application = { id = "com.varabyte.kobweb.application", version.ref = "kobweb" }
kobweb-library = { id = "com.varabyte.kobweb.library", version.ref = "kobweb" }
kobwebx-markdown = { id = "com.varabyte.kobwebx.markdown", version.ref = "kobweb" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization-plugin" }
